name: Translate Markdown Files

on:
  push:
    paths:
      - '**/*.md'
    branches:
      - main  

jobs:
  call-translate-markdown:
    uses: rimoapp/bilingual-github/.github/workflows/translate-markdown.yml@main
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      PAT: ${{ secrets.GITHUB_TOKEN }}
    with:
      target_repo: rimoapp/bilingual-testing  
      
