name: Translate Issue Comments

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  call-translate-comments:
    uses: rimoapp/bilingual-github/.github/workflows/translate-comments.yml@main
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    with:
      issue_number: ${{ github.event.issue.number }}
      comment_id: ${{ github.event.comment.id }}