name: Translate GitHub Issues

on:
  issues:
    types:
      - opened
      - edited

jobs:
  call-translate-issues:
    uses: rimoapp/bilingual-github/.github/workflows/translate-issues.yml@main
    secrets: # Pass the GITHUB_TOKEN here
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # Pass this if required
