name: Translate GitHub Pull Requests

on:
  pull_request:
    types:
      - labeled
      - edited
  issue_comment:
    types:
      - created
      - edited

jobs:
  translate-pr:
    if: |
      (github.event_name == 'pull_request' && 
        (github.event.label.name == 'need translation' ||
         (github.event.action == 'edited' && contains(github.event.pull_request.labels.*.name, 'need translation')))) ||
      (github.event_name == 'issue_comment' && github.event.issue.pull_request)
    uses: rimoapp/bilingual-github/.github/workflows/translate-prs.yml@main
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    with:
      pr_number: ${{ github.event.pull_request.number || github.event.issue.number }}
      comment_id: ${{ github.event.comment.id || '' }}
