name: Trigger Translation

on:
  pull_request:
    types:
      - labeled
      - edited
  issue_comment:
    types:
      - created
      - edited
  pull_request_review_comment:
    types:
      - created
      - edited
  issues:
    types:
      - labeled
      - edited
  pull_request_review:
    types:
      - submitted

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  trigger-translation:
    if: |
      (
        github.event_name == 'pull_request' &&
        (
          github.event.label.name == 'need translation' ||
          (github.event.action == 'edited' && contains(github.event.pull_request.labels.*.name, 'need translation'))
        )
      ) ||
      (
        github.event_name == 'issue_comment' &&
        (
          (github.event.issue.pull_request && contains(github.event.issue.labels.*.name, 'need translation')) ||
          (!github.event.issue.pull_request && contains(github.event.issue.labels.*.name, 'need translation'))
        )
      ) ||
      (
        github.event_name == 'pull_request_review_comment' &&
        contains(github.event.pull_request.labels.*.name, 'need translation')
      ) ||
      (
        github.event_name == 'issues' &&
        (
          github.event.label.name == 'need translation' ||
          (github.event.action == 'edited' && contains(github.event.issue.labels.*.name, 'need translation'))
        )
      ) ||
      (
        github.event_name == 'pull_request_review' &&
        contains(github.event.pull_request.labels.*.name, 'need translation')
      )
    uses: rimoapp/bilingual-github/.github/workflows/translate.yml@refs/heads/main
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      issue_number: ${{ github.event.issue.number || github.event.pull_request.number }}
      comment_id: ${{ github.event.comment.id || github.event.review_comment.id || github.event.review.id || '' }}
      target_repository: ${{ github.repository }}   
